### ISSUE TITLE
PHP version used should abide by composer's version constraint

### ISSUE THREAD

**Issue by ikari7789** [cloudfoundry/php-buildpack#245] opened 2018-01-26 02:44 UTC
If you specify a PHP version in both `composer.json` and `.bp-config/options.json`, the buildpack will default to using the version defined in `composer.json`, but it doesn't take into account the version constraint.

https://github.com/cloudfoundry/php-buildpack/blob/2b2fa0414be3ff0b4c593e54b7b130c340e00338/lib/php/extension.py#L125-L127

So given the following configuration:

.bp-config/options.json
```
{
  "PHP_VERSION": "{PHP_71_LATEST}"
}
```

composer.json
```
{
  "require": {
      "php": ">=7.0.0"
  }
}
```

The buildpack would default to 7.0.X even though 7.1.X also applies to `>=7.0.0`.
This, personally feels a little unintuitive and I would expect to be able to run against 7.1.X without needing to remove the version constraint from my composer.json (which serves a greater purpose of preventing the code to be installed on a version lower than the specified value).

**Comment by dmikusa-pivotal** [comment] 2018-01-26 06:06
This is currently working as designed.  See the docs here, which explain the limitation.

https://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html

Essentially, what this boils down to is that PHP is not installed.  Composer is not installed.  Thus when the buildpack runs, we cannot run Composer to parse composer.json and pull out the version of PHP that is installed.  That leaves us with having to reimplement the logic to do this in the buildpack.  This is bad because we don't want to reimplement the logic.  As a compromise, we implemented a subset, what we could easily and reliably do, in the buildpack.

I agree it's not ideal and hope it can be improved at some point.  

@sclevine - Maybe that's a goal for the buildpack rewrite?

**Comment by ikari7789** [comment] 2018-01-26 06:54
@dmikusa-pivotal Still seems like it's not using an appropriate version?
That really doesn't feel like a strong argument to me.

The composer.json is already having the `php` value parsed from it and having the version determined.

https://github.com/cloudfoundry/php-buildpack/blob/86861d985f6240ba5a8ec445c2a7b8255a5df22b/extensions/composer/extension.py#L102-L120

Seems to me that the version specified in `.bp-options/options.json` should be respected if it falls within the value specified by the `composer.json`. Even if `.bp-options/options.json` is ignored, I wouldn't expect `>=7.0.0` to use `7.0.X` instead of `7.1.X`.

As far as I can tell, it's currently impossible to have a package that specifies `"php": ">=7.0.0"` use PHP 7.1.X. Increasing that requirement in composer.json will unnecessarily make the package less flexible. Let alone the fact that you could specify a version restraint such as `~7.0` or `>=7.0.0 <7.0.5`. Would these use cases also be supported given the current logic?

**Comment by ikari7789** [comment] 2018-01-26 07:17
My personal opinion on how the selected version should be determined is as such:

- Remove the translation of '>=' to '~>'. This has a different meaning and is unexpected.
- Determine `max_satisfying` from composer.json.
- If `.bp-config/options.json` also specifies a version:
  - If `options.json` > composer.json value and < composer.json max_satisfying, use it (allows user to pin to a specific version).
- Otherwise fail to deploy?

**Comment by sclevine** [comment] 2018-02-02 15:57
As Dan mentioned, we agree that this is not ideal. We would welcome a PR that improves this behavior, so long as it doesn't break any properly configured PHP buildpack apps.

Otherwise, we will address this when we re-write the PHP buildpack using libbuildpack. The PHP buildpack is the only remaining Cloud Foundry buildpack that hasn't been re-written in Go using [libbuildpack](https://github.com/cloudfoundry/libbuildpack).

**Comment by ameyer-pivotal** [comment] 2018-09-06 16:08
@ikari7789 @sclevine @dmikusa-pivotal Closing this issue due to inactivity. Please feel free to reopen as needed.

**Comment by ameyer-pivotal** [comment] 2018-09-06 16:11
@ikari7789 @sclevine @dmikusa-pivotal Actually, decided to keep this open to evaluate after converting this buildpack to `libbuildpack`. Please ignore the story referenced above, as we'll continue to track with the original story (https://www.pivotaltracker.com/story/show/154655683).

**Comment by dfreilich** [comment] 2019-06-04 19:49
@dmikusa-pivotal Is this taken care of in the composer-cnb? Should I close this issue?

**Comment by dmikusa-pivotal** [comment] 2019-06-05 16:19
@dfreilich - The PHP Composer CNB is just fishing the version information out of composer.json|lock, it's not interpreting it. So it just passes the semver string through to libcfbuildpack which seems to do the right thing, at least from initial testing. I haven't looked too much though, and don't know exactly how libcfbuildpack is handling that.

**Comment by dfreilich** [comment] 2019-08-06 20:15
@ikari7789 This is fixed in the new [php-composer-cnb](github.com/cloudfoundry/php-composer-cnb). 

Thanks for pointing this out!

**Closed by dfreilich** 2019-08-06 20:15 UTC
Labels: unscheduled
