### ISSUE TITLE
**Release:** php-buildpack 4.4.44

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/php-buildpack#519] opened 2021-07-11 22:03 UTC
**Dependency Changes:**

```diff
nginx:
- 1.21.0
+ 1.21.1

php:
- 7.3.27
- 7.4.19
- 8.0.6
+ 7.3.29
+ 7.4.21
+ 8.0.8

```

**New Commits on Develop**:

f55a5789 Updates defaults/options.json to use newer default PHP version
84af5734 Update libbuildpack
cd8557c9 Update nginx default version patch
ca9aa118 Auto merge pull request 518
2e28e5ff Add nginx 1.21.1, remove nginx 1.21.0
4d669fb8 Update default version
797fe6d3 Auto merge pull request 515
1a541e70 Add php 7.4.21, remove php 7.4.19
44094b68 Auto merge pull request 514
d376579e Add php 8.0.8, remove php 8.0.6
47d261c3 Auto merge pull request 513
f17402b1 Add php 7.3.29, remove php 7.3.27

Refer to [release instructions](https://docs.cloudfoundry.org/buildpacks/releasing_a_new_buildpack_version.html).

**Comment by arjun024** [comment] 2021-07-14 15:52
Duplicate of #516

**Closed by arjun024** 2021-07-14 15:52 UTC
Labels: unscheduled
