### ISSUE TITLE
Load ini files from PHP_INI_SCAN_DIR during staging

### ISSUE THREAD

**Issue by mjanser** [cloudfoundry/php-buildpack#267] opened 2018-06-20 14:21 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
N/A

What version of the buildpack you are using?
4.3.56

If you were attempting to accomplish a task, what was it you were attempting to do?
I'd like to use custom PHP ini files from `PHP_INI_SCAN_DIR` during staging. For this I added the file .bp-config/php/php.ini.d/test.ini with the following content:
```
[PHP]
memory_limit = 500M
```

What did you expect to happen?
The custom ini file is used during staging, especially for the composer run. I except that when reading https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html.

What was the actual behavior?
According to the debug output (BP_DEBUG=True) there is no environment variable `PHP_INI_SCAN_DIR` set when running composer. Therefore the custom ini file is not loaded.

I added a custom script to `composer.json` which just runs `php --ini`. The output during staging is the following:
```
> php --ini
   Configuration File (php.ini) Path: /tmp/build/931e8e8a/binary-builder/ports/x86_64-linux-gnu/php7/7.1.17/lib
   Loaded Configuration File:         /tmp/php.ini
   Scan for additional .ini files in: (none)
   Additional .ini files parsed:      (none)
```

Here are the files I used for a simple test.
composer.json
```
{
    "name": "myapp",
    "type": "project",
    "require": {
        "php": "7.1.*"
    },
    "scripts": {
        "post-install-cmd": [
            "php --version",
            "php --ini"
        ]
    }
}
```
manifest.yml
```
---
applications:
- name: myapp
  memory: 300M
  disk_quota: 900M
  instances: 1
  buildpack: php_buildpack
  env:
      BP_DEBUG: "True"
```
.bp-config/options.json
```
{
  "PHP_VM": "php",
  "ZEND_EXTENSIONS": [
    "opcache"
  ],
  "COMPOSER_VENDOR_DIR": "vendor",
  "COMPOSER_INSTALL_OPTIONS": [
    "--no-dev",
    "--no-interaction",
    "--no-suggest",
    "--prefer-dist",
    "--optimize-autoloader"
  ],
  "PHP_MODULES": [
    "cli"
  ]
}
```
.bp-config/php/php.ini.d/test.ini
```
[PHP]
memory_limit = 500M
```

**Comment by dmikusa-pivotal** [comment] 2018-06-21 03:15
I think that this is currently the expected behavior.  The buildpack doesn't reference the ini fragments.  It's not intentional, it just hasn't been written to do this.

I'm +1 for making it do this though.  It makes sense and would be a good improvement.

Any interest in submitting a PR?  I think you'd just need to modify the env that we build for running composer [here](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L356-L378).  You could point that directly to the `.bp-config/php/php.ini.d` folder.

For some background on the `php.ini` in staging.  You'll see [here](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L403-L413) that the buildpack copies and rewrites the `php.ini` file.  It's doing this to update path references in the config file.  This is because paths at staging and paths at runtime are totally different.  I don't believe that we rewrite php.ini snippets, so I don't think we need to worry about this really.  I just wanted to point it out cause at some point, someone may want to set a path in their php.ini snippet.  That would be a problem because the path would never match staging & runtime, so it would have to be a relative path.

Hope that helps!

**Comment by ndon55555** [comment] 2019-07-23 20:08
FYI, this is fixed in the php-composer-cnb. It will set PHP_INI_SCAN_DIR to reference your user specified config fragments.

**Comment by dfreilich** [comment] 2019-07-24 16:08
@mweibel I'm closing this for now. If you're interested on making a PR for the existing PHP buildpack, we can prioritize that, but as it's solved in the new cloud native buildpacks, it should be fine.

**Closed by dfreilich** 2019-07-24 16:08 UTC
Labels: unscheduled
