### ISSUE TITLE
HTTP_X_FORWARDED_FOR missing when using HTTPD web server

### ISSUE THREAD

**Issue by bbodenmiller** [cloudfoundry/php-buildpack#457] opened 2021-01-16 04:09 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```bash
$ cf curl v2/info && cf version
{
   "name": "Pivotal Application Service",
   "build": "2.7.29-build.5",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-7/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "xxxxxxxxx",
   "token_endpoint": "xxxxxxxxxxxxxx",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "xxxxxxxxxxxxx",
   "app_ssh_host_key_fingerprint": "xxxxxxxxxxxxxxxxxx",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "xxxxxxxxxxxxxxx",
   "api_version": "2.139.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "xxxxxxxxx",
   "user": "xxxxxxxx"
}
cf.exe version 6.53.0+8e2b70a4a.2020-10-01

```

What version of the buildpack you are using?

> Buildpack version 4.4.29

If you were attempting to accomplish a task, what was it you were attempting to do?

Trying to read `HTTP_X_FORWARDED_FOR` server variable (`$_ENV['HTTP_X_FORWARDED_FOR']` & `$_SERVER['HTTP_X_FORWARDED_FOR']`

What did you expect to happen?

Should be populated when using HTTPD web server

What was the actual behavior?

It is not populated when using HTTPD web server however is populated when using nginx web server

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sophiewigmore** [comment] 2021-02-17 16:48
Hi there @bbodenmiller. Could you provide more information about your app so we can try to reproduce this?
We were not able to reproduce this error. We `cf push`ed a simple PHP app that contains just an `index.php` with:
```  
<?php
   echo 'ENV VAR IS SET ' .$_ENV['HTTP_X_FORWARDED_FOR'] . '!';
?>
```
This app uses the HTTPD web server, and the app output the `HTTP_X_FORWARDED_FOR` IP address.

**Comment by bbodenmiller** [comment] 2021-02-18 02:30
@sophiewigmore here's what I tested:

`index.php`:
```php
<?php

$headers =  getallheaders();

foreach($headers as $key=>$val){
  echo $key . ': ' . $val . '<br>';
}

phpinfo();

?>
```

```
cf push php-test --random-route -b php_buildpack_latest
```

On `index.php` I see

![image](https://user-images.githubusercontent.com/1192780/108296010-9881dc80-714d-11eb-9705-e8ef65eb423f.png)

If I add `.bp-config/options.json`

```json
{
    "WEB_SERVER": "nginx"
}
```

```
cf push php-test --random-route -b php_buildpack_latest
```

Now on `index.php` I see

![image](https://user-images.githubusercontent.com/1192780/108296046-a59ecb80-714d-11eb-970f-975e5acac626.png)

**Comment by menehune23** [comment] 2021-09-08 18:45
@bbodenmiller It seems the issue might be elsewhere, as @sophiewigmore was able to provide a minimal example that demonstrates the env var's presence while using HTTPD. Can you try changing your `index.php` to what she had and see if there is still a problem?

I'll close this for now, but feel free to reopen if you've narrowed this down to the buildpack itself, and we can go from there.

**Closed by menehune23** 2021-09-08 18:45 UTC
Labels: unscheduled
