### ISSUE TITLE
Services defined within extension `service_commands` are not restarted on exit

### ISSUE THREAD

**Issue by phpbg** [cloudfoundry/php-buildpack#330] opened 2020-01-08 16:09 UTC
Hi,

I'm using a service_command from an extension to run a process.
This process is a php process intended to run indefinitely.
As stated from the doc, if my process crash the container should be restarted:

> The service_commands method gives extension authors the ability to contribute a set of services that need to be run. These commands are run and should continue to run. If any service exits, the process manager will halt all of the other services and the application will be restarted by Cloud Foundry.

It is **not** restarted **at all**.

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
* **api_version: 2.141.0**
* **cf version 6.47.2+d526c2cb3.2019-11-05**

What version of the buildpack you are using?
**4.4.5**

If you were attempting to accomplish a task, what was it you were attempting to do?
1. Create a service:

```python
def service_commands(ctx):
	return {
		"workerservice": ('php /app/scripts/worker.php',)
	}
```
2. Create a simple process that exits (this process is intended to be a long running process, but we emulate an exit):

```php
echo "Worker started\n";
sleep(30);
throw new Exception("Worker exited");
```

What did you expect to happen?
**The process (or the container) should be restarted after dying**

What was the actual behavior?
**The process dies and is never restarted (nor the container)**

Log output:
```
2020-01-08T17:03:15.97+0100 [APP/PROC/WEB/0] OUT 17:03:15 workerservice| Worker started
2020-01-08T17:03:45.96+0100 [APP/PROC/WEB/0] OUT 17:03:45 workerservice| PHP Fatal error:  Uncaught Exception: Worker exited in /home/vcap/app/scripts/worker.php:9
2020-01-08T17:03:45.96+0100 [APP/PROC/WEB/0] OUT 17:03:45 workerservice| Stack trace:
2020-01-08T17:03:45.96+0100 [APP/PROC/WEB/0] OUT 17:03:45 workerservice| #0 {main}
2020-01-08T17:03:45.96+0100 [APP/PROC/WEB/0] OUT 17:03:45 workerservice|   thrown in /home/vcap/app/scripts/worker.php on line 9
```

**Comment by dmikusa-pivotal** [comment] 2020-01-08 17:58
The intent isn't to have your process restarted. The service commands allow you to define services that should either all be running or that should indicate a crash. If there is a crash, the expected behavior is that your entire app instance in CF would restart, since CF would see the app instance exited.

It sounds like your app instance isn't exiting, is that correct?

**Comment by dmikusa-pivotal** [comment] 2020-01-08 19:02
For what it's worth, you might want to look at using https://docs.cloudfoundry.org/devguide/multiple-processes.html#push-with-multiple-processes instead. You would just set your Profile to have `web: $HOME/.bp/bin/start` which would start the normal stuff. Then you can have any number of additional processes to run your workers.

That way is better because it doesn't depend on a feature only in the PHP buildpack & your web and worker processes will be isolated in different containers. This means they can be scaled individually.

Hope that helps!

**Comment by phpbg** [comment] 2020-01-09 09:13
> It sounds like your app instance isn't exiting, is that correct?

That's right, thanks for the clarification.
It sounds like a bug because it is not what documentation states about `service_commands`.

In the meantime I'll have a look to your link above.

**Comment by phpbg** [comment] 2020-01-09 10:44
> 
> For what it's worth, you might want to look at using https://docs.cloudfoundry.org/devguide/multiple-processes.html#push-with-multiple-processes instead. You would just set your Profile to have `web: $HOME/.bp/bin/start` which would start the normal stuff. Then you can have any number of additional processes to run your workers.

I did manage to get my process running.
But again, when it dies, no one restarts it.
Sounds primising, but still beta yet...

```
11:34:44.213: [CELL.0] Container became healthy
11:34:55.432: [APP/PROC/WORKER.0] PHP Fatal error:  Uncaught Exception: Worker exited in /home/vcap/app/scripts/worker.php:8
11:34:55.432: [APP/PROC/WORKER.0] Stack trace:
11:34:55.432: [APP/PROC/WORKER.0] #0 {main}
11:34:55.432: [APP/PROC/WORKER.0]   thrown in /home/vcap/app/scripts/worker.php on line 8
```

**Comment by dmikusa-pivotal** [comment] 2020-01-09 20:05
>Sounds promising, but still beta yet...

It is beta in that the API may yet still change. It's probably not good to integrate this into any complicated scripts, as cli commands might change too. That said, the actual code running your apps should work just fine.

>But again, when it dies, no one restarts it.

Can you elaborate on what you're seeing? How are you determining that it's working? 

Both options work fine for me.

From `cf logs`...

```
   2020-01-09T15:04:28.01-0500 [CELL/0] OUT Container became healthy
   2020-01-09T15:04:56.34-0500 [APP/PROC/WEB/0] OUT 20:04:56 worker  | PHP Fatal error:  Uncaught Exception: Worker exited in /home/vcap/app/worker.php:4
   2020-01-09T15:04:56.34-0500 [APP/PROC/WEB/0] OUT 20:04:56 worker  | Stack trace:
   2020-01-09T15:04:56.34-0500 [APP/PROC/WEB/0] OUT 20:04:56 worker  | #0 {main}
   2020-01-09T15:04:56.34-0500 [APP/PROC/WEB/0] OUT 20:04:56 worker  |   thrown in /home/vcap/app/worker.php on line 4
   2020-01-09T15:04:56.71-0500 [APP/PROC/WEB/0] OUT Exit status 255
```

From `cf events`:

```
2020-01-09T15:05:02.00-0500   app.crash                  php-info             index: 0, reason: CRASHED, cell_id: 18751cdc-f831-44cf-afdf-5e7730e7444e, instance: efc5e319-deaf-4dd6-627a-e964, exit_description: APP/PROC/WEB: Exited with status 255
2020-01-09T15:05:02.00-0500   audit.app.process.crash    web                  index: 0, reason: CRASHED, cell_id: 18751cdc-f831-44cf-afdf-5e7730e7444e, instance: efc5e319-deaf-4dd6-627a-e964, exit_description: APP/PROC/WEB: Exited with status 255
```

It is only down for a split second, but it's definitely crashing and restarting.

**Comment by phpbg** [comment] 2020-01-14 13:17
The main difference between you and me in the logs is `Exit status 255`.

```
2020-01-09T15:04:56.71-0500 [APP/PROC/WEB/0] OUT Exit status 255
```

Do you observe another crash a few seconds later? That would proove that the container restarted. On my side I do not see any further log.

Could it come from a different api version? or differents parameters?

**Comment by dmikusa-pivotal** [comment] 2020-01-14 13:59
It's hard to say. For what it's worth, I ran this test against API `"2.144.0"`.

If you never see the process exit, my suggestion would be to `cf ssh` into the container and look at the process state. Try `ps auxf` and see what that looks like. It should give you a process tree of what's running. 

Normally with the PHP buildpack, you'd see something like this:

```
vcap           6  0.2  0.0 244256 14720 ?        Ssl  Jan09  18:05 python /home/vcap/app/.bp/bin/start
vcap         101  0.0  0.0   4628   820 ?        S    Jan09   0:00  \_ /bin/sh -c $HOME/httpd/bin/apachectl -f "$HOME/httpd/conf/httpd.conf" -k start -DFOREGROUND
vcap         102  0.0  0.0   4628   868 ?        S    Jan09   0:00  |   \_ /bin/sh /home/vcap/app/httpd/bin/apachectl -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOR
vcap         104  0.0  0.0  67648  4920 ?        S    Jan09   0:13  |       \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         107  0.0  0.0  67308  2784 ?        S    Jan09   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         108  0.0  0.0 1995020 4420 ?        Sl   Jan09   0:01  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         109  0.0  0.0 1995020 3788 ?        Sl   Jan09   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         110  0.0  0.0 1995020 3788 ?        Sl   Jan09   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         210  0.0  0.0 2060556 4192 ?        Sl   Jan11   0:01  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         105  0.0  0.0   4628   868 ?        S    Jan09   0:00  \_ /bin/sh -c $HOME/php/sbin/php-fpm -p "$HOME/php/etc" -y "$HOME/php/etc/php-fpm.conf" -c "$HOME/php/et
vcap         111  0.0  0.1 692220 44100 ?        Ss   Jan09   0:15      \_ php-fpm: master process (/home/vcap/app/php/etc/php-fpm.conf)
vcap         194  0.0  0.0 692784 24168 ?        S    Jan09   0:00          \_ php-fpm: pool www
vcap         195  0.0  0.1 993236 38872 ?        S    Jan09   0:00          \_ php-fpm: pool www
```

`python /home/vcap/app/.bp/bin/start` is what spawns everything, so in your case assuming you're using the `service_commands` approach and not the `Procfile` approach, if the process hasn't exited, you'd likely still see it listed as a third sub-process of the `start` script.

Let me know what you see.

**Comment by phpbg** [comment] 2020-01-14 14:26
That's quite interesting...
Before my process dies, I can see the tree and it looks good:
```
vcap           7  4.0  0.0 317992 14604 ?        Ssl  15:20   0:00 python /home/vcap/app/.bp/bin/start
vcap         106  0.1  0.0   4632   820 ?        S    15:20   0:00  \_ /bin/sh -c php /app/scripts/worker.php
vcap         107  0.2  0.0 264116 24280 ?        S    15:20   0:00  |   \_ php /app/scripts/worker.php
vcap         108  0.2  0.0   4632   816 ?        S    15:20   0:00  \_ /bin/sh -c $HOME/httpd/bin/apachectl -f "$HOME/httpd/conf/httpd.conf" -k start -DFOREGROUND
vcap         109  0.0  0.0   4632   820 ?        S    15:20   0:00  |   \_ /bin/sh /home/vcap/app/httpd/bin/apachectl -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         112  0.2  0.0  63496  4720 ?        S    15:20   0:00  |       \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         113  0.0  0.0 2056404 3760 ?        Sl   15:20   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         114  0.0  0.0 1990868 3760 ?        Sl   15:20   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         115  0.0  0.0 1990868 3760 ?        Sl   15:20   0:00  |           \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         110  0.2  0.0   4632   876 ?        S    15:20   0:00  \_ /bin/sh -c $HOME/php/sbin/php-fpm -p "$HOME/php/etc" -y "$HOME/php/etc/php-fpm.conf" -c "$HOME/php/etc"
vcap         156  0.8  0.0 405648 26032 ?        Ss   15:20   0:00      \_ php-fpm: master process (/home/vcap/app/php/etc/php-fpm.conf)
vcap         201  0.0  0.0 405780  6912 ?        S    15:20   0:00          \_ php-fpm: pool www
vcap         202  0.0  0.0 405780  6912 ?        S    15:20   0:00          \_ php-fpm: pool www
```

But after a few seconds, when the process dies, here is what I'am getting:
```
vcap         109  0.0  0.0   4632   820 ?        S    15:20   0:00 /bin/sh /home/vcap/app/httpd/bin/apachectl -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         112  0.0  0.0  63496  4720 ?        S    15:20   0:00  \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         113  0.0  0.0 2056404 3760 ?        Sl   15:20   0:00      \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         114  0.0  0.0 1990868 3760 ?        Sl   15:20   0:00      \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         115  0.0  0.0 1990868 3760 ?        Sl   15:20   0:00      \_ /app/httpd/bin/httpd -f /home/vcap/app/httpd/conf/httpd.conf -k start -DFOREGROUND
vcap         156  0.1  0.0 405648 26032 ?        Ss   15:20   0:00 php-fpm: master process (/home/vcap/app/php/etc/php-fpm.conf)
vcap         201  0.0  0.0 405780  6912 ?        S    15:20   0:00  \_ php-fpm: pool www
vcap         202  0.0  0.0 405780  6912 ?        S    15:20   0:00  \_ php-fpm: pool www
```

I seems that the python wrapper died, but apache and fpm process are still alive...

**Comment by phpbg** [comment] 2020-01-14 14:44
I got it !

I was using another extension, so I tried to remove it, and it fixed the issue.

That extension was running a service, but using `preprocess_commands (plus detach process in background)` instead of `service_commands`.
I fixed it by moving the service to `service_commands`, and now everything works like a charm.

I guess the python service manager got lost, and there is probably room for improvement.
I'll let you decide wether you want to close this issue or not...

**Comment by dmikusa-pivotal** [comment] 2020-01-14 19:40
Excellent. Not totally sure what happened here. It could be something with loading the processes to run or running them which got messed up in this scenario. Hard to say exactly without a repro test case.

My $0.02 would be to close this out. The way the current php-buildpack allows extensions is going away in the PHP CNB world. The CNBs use Golang and so we can't support Python style extensions. There are, for the most part, ways to work around this but it will require some migration if you're currently using PHP buildpack Python style extensions. FYI.

**Closed by dmikusa-pivotal** 2020-01-14 19:40 UTC
Labels: unscheduled
