### ISSUE TITLE
NGINX_19_LATEST not working?

### ISSUE THREAD

**Issue by pepijnblom** [cloudfoundry/php-buildpack#131] opened 2016-01-30 20:06 UTC
Hi I'm deploying an app with the following options.json and it's failing with NGINX_19_LATEST:

```
{
  "WEB_SERVER": "nginx",
  "NGINX_VERSION": "{NGINX_19_LATEST}",
  "PHP_VM": "hhvm",
  "HHVM_VERSION": "3.6.1",
  "COMPOSER_VENDOR_DIR": "htdocs/vendor",
  "WEBDIR": "htdocs/public"
}
```

Error:
```
Installing Nginx
Traceback (most recent call last):
  File "/tmp/buildpacks/php-buildpack/scripts/compile.py", line 51, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 189, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/php-buildpack/lib/nginx/extension.py", line 39, in compile
    .package('NGINX')
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/builder.py", line 165, in package
    self._installer.install_binary(key)
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/cloudfoundry.py", line 197, in install_binary
    url = self._ctx['%s_DOWNLOAD_URL' % installKey]
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 151, in __getitem__
    return self.format(dict.__getitem__(self, key))
  File "/tmp/buildpacks/php-buildpack/lib/build_pack_utils/utils.py", line 143, in format
    newVal = val.format(**self)
KeyError: u'NGINX_19_LATEST'
```

**Comment by flavorjones** [comment] 2016-01-30 20:33
Hi,

Thanks for opening this issue.

I'm not able to reproduce what you're seeing, unfortunately. I'm using php-buildpack v4.3.3. What version are you using?

Worth noting that `NGINX_19_LATEST` was first introduced in v4.0.0, so if you're on an older version than that, it's not going to be supported.

You can see the version of the buildpack by running `cf buildpacks`, or else in your staging output you should see something like:

```
-------> Buildpack version 4.3.3
```

**Comment by pepijnblom** [comment] 2016-02-02 05:56
@flavorjones Thanks for the feedback, I have since tried pushing with the added -b argument pointing to this repo and things are working now. 

I forgot to check the cf buildpacks list before I ran the push, but now it shows the following version:
```
buildpack                                 position   enabled   locked   filename
php_buildpack                         8              true         false      php_buildpack-cached-v4.1.5.zip
```

The output from the push however shows this:
```
-------> Buildpack version 4.3.4
```

Is there  a way to set the buildpack version in a config file without having to use the -b argument on each push?

**Comment by flavorjones** [comment] 2016-02-02 15:38
@pepijnblom The Cloud Controller will remember the URL you used in the past to specify a buildpack. It's a "sticky" metadata attribute.

You can see this and other "sticky" attributes if you use `cf create-app-manifest`, which will generate an application manifest for an app that's been pushed.

Make sense?

I'm going to close this ticket, but I'm happy to continue the conversation.

**Closed by flavorjones** 2016-02-02 15:38 UTC
Labels: needs more information
