### ISSUE TITLE
How to add zend_loader extension not included in the list?

### ISSUE THREAD

**Issue by wangping710** [cloudfoundry/php-buildpack#52] opened 2015-03-14 08:03 UTC
sorry， i not reply everybody in time

i need Zend Guard Loader，studying to how put it in the buildpack with custom extension .

is there a more simple way，please？

https://github.com/cloudfoundry/php-buildpack/issues/51

**Comment by flavorjones** [comment] 2015-03-15 19:05
Closing; duplicate of #51 which I've reopended.

**Closed by flavorjones** 2015-03-15 19:05 UTC
