### ISSUE TITLE
cakephp + composer problems

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/php-buildpack#193] opened 2017-02-21 11:59 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
jeandeklerk at Jeans-MacBook-Pro in /tmp/my_app_name
$ cf curl /v2/info
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.74.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "logging_endpoint": "wss://loggregator.run.pivotal.io:443",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "user": "d96e6ba9-bd4d-486e-b7eb-0f2eb0df8967"
}
jeandeklerk at Jeans-MacBook-Pro in /tmp/my_app_name
$ cf version
cf version 6.22.1+6b7af9c-2016-09-24
```

What version of the buildpack you are using?

Whatever is on PWS.

If you were attempting to accomplish a task, what was it you were attempting to do?

Push the generic `bake` app (the thing cakephp prebuilds as a starter project).

What did you expect to happen?

It runs properly.

What was the actual behavior?

It can't find `vendor/autoloader.php`.

```
Fatal error: require(): Failed opening required '/home/vcap/app/htdocs/vendor/autoload.php' (include_path='.:') in /private/tmp/my_app_name/bin/cake.php on line 31
```

Furthermore, when I `cf ssh` in I see that `/home/vcap/app/htdocs` is entirely missing a `vendor` folder, despite `bake` giving me a `composer.json`.

**Comment by jadekler** [comment] 2017-02-21 12:08
Including a `.bp-config/options.js` with

```
{
  "COMPOSER_VENDOR_DIR": "/home/vcap/app/htdocs"
}
```

Does not seem to change anything, either.

**Comment by sclevine** [comment] 2017-02-21 16:09
@dgodd @dmikusa-pivotal any thoughts on this?

**Comment by dmikusa-pivotal** [comment] 2017-02-21 16:15
Not familiar with CakePHP itself.  I know of it and that we have a couple integration tests [1](https://github.com/cloudfoundry/php-buildpack/tree/master/cf_spec/fixtures/cake_with_local_dependencies) and [2](https://github.com/cloudfoundry/php-buildpack/tree/master/cf_spec/fixtures/cake_with_remote_dependencies) , but I don't know much beyond that.  Never used it to build an app.

@jadekler - Any chance you could provide an exact set of steps to reproduce this issue?

**Comment by lbayerl** [comment] 2017-02-21 16:35
Can you please share your full `options.json` as well as you're `composer.json`? I am pretty sure it's not about cf itself.

**Comment by jadekler** [comment] 2017-02-21 16:35
@lbayerl On it

**Comment by jadekler** [comment] 2017-02-21 16:36
Composer.json:

```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.4.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true
}
```

Options.json:

```
{
  "WEBDIR": "public",
  "LIBDIR": "mylibs"
}
```

**Comment by jadekler** [comment] 2017-02-21 16:36
ps. Same problem with that `options.json` as without any `options.json`

**Comment by lbayerl** [comment] 2017-02-21 16:37
what about e.g.

`  "COMPOSER_INSTALL_OPTIONS": [
    "--no-dev --optimize-autoloader --no-progress --no-interaction"
  ],`

in your `options.json`? So did you check all requirements for running a PHP app with cf?

**Comment by jadekler** [comment] 2017-02-21 16:38
And the specific error:

```
2017-02-21T14:12:32.44+0200 [RTR/4]      OUT my-cool-app.cfapps.io - [2017-02-21T12:12:32.443+0000] "GET / HTTP/1.1" 500 0 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "10.10.66.28:62859" "10.10.148.103:60088" x_forwarded_for:"154.66.90.37" x_forwarded_proto:"http" vcap_request_id:"41f0dd8a-3c66-4524-58a0-3c5cecf92c84" response_time:0.00340014 app_id:"5f3b787f-888f-436e-8a80-56d724a3fbd7" app_index:"0" x_b3_traceid:"2a3bd80c09d6277f" x_b3_spanid:"2a3bd80c09d6277f" x_b3_parentspanid:"-"
2017-02-21T14:12:32.48+0200 [APP/PROC/WEB/0]OUT 12:12:32 httpd   | [Tue Feb 21 12:12:32.457742 2017] [proxy_fcgi:error] [pid 54:tid 140493346305792] [client 154.66.90.37:12032] AH01071: Got error 'PHP message: PHP Warning:  require(/home/vcap/app/public/vendor/autoload.php): failed to open stream: No such file or directory in /home/vcap/app/public/webroot/index.php on line 27\nPHP message: PHP Fatal error:  require(): Failed opening required '/home/vcap/app/public/vendor/autoload.php' (include_path='../lib/php:/home/vcap/app/mylibs') in /home/vcap/app/public/webroot/index.php on line 27\n'
2017-02-21T14:12:32.48+0200 [APP/PROC/WEB/0]OUT 12:12:32 httpd   | 154.66.90.37 - - [21/Feb/2017:12:12:32 +0000] "GET / HTTP/1.1" 500 - vcap_request_id=41f0dd8a-3c66-4524-58a0-3c5cecf92c84 peer_addr=10.10.81.5
```

I'll add that I do see the buildpack doing the whole `Installing cakephp, installing x, y, z` but I don't see any `vendor` directory when I `cf ssh` in

**Comment by jadekler** [comment] 2017-02-21 16:39
@lbayerl Is that an option in the `manifest.yml` I should be specifying? And, what `requirements` are you referring to? The only thing the [buildpack docs](http://docs.cloudfoundry.org/buildpacks/php/index.html) tells me about is `Supported Software and Versions`; I don't see a requirements section.

**Comment by lbayerl** [comment] 2017-02-21 16:39
see e.g. this [project](https://github.com/lbayerl/symfony-on-swisscomdev) I created, it's Symfony not Cake, but you will find a couple of composer related topics with Cloud Foundry. I am sure your composer isn't installing anything that's why your vendor folder is empty/does not exist.

**Comment by dmikusa-pivotal** [comment] 2017-02-21 16:40
@jadekler - Full output from staging would be helpful if you could include that.

**Comment by jadekler** [comment] 2017-02-21 16:40
@lbayerl Giving it another go with your [options.json](https://github.com/lbayerl/symfony-on-swisscomdev/blob/master/.bp-config/options.json)

**Comment by jadekler** [comment] 2017-02-21 16:41
@dmikusa-pivotal Will get that to you in a sec

**Comment by jadekler** [comment] 2017-02-21 16:42
No dice @lbayerl.

@dmikusa-pivotal:

```
jeandeklerk at Jeans-MacBook-Pro in /tmp/my_app_name
$ cf logs my-cool-app
Connected, tailing logs for app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...

2017-02-21T18:42:36.65+0200 [RTR/2]      OUT my-cool-app.cfapps.io - [2017-02-21T16:42:36.639+0000] "GET / HTTP/1.1" 500 0 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "10.10.2.141:35770" "10.10.148.98:60055" x_forwarded_for:"197.245.88.228" x_forwarded_proto:"http" vcap_request_id:"0d1a4bd5-8b80-4d5a-6d1e-3f7eea6288d4" response_time:0.012002053 app_id:"5f3b787f-888f-436e-8a80-56d724a3fbd7" app_index:"0" x_b3_traceid:"88f50d1a9d1162a6" x_b3_spanid:"88f50d1a9d1162a6" x_b3_parentspanid:"-"
2017-02-21T18:42:36.70+0200 [APP/PROC/WEB/0]OUT 16:42:36 httpd   | [Tue Feb 21 16:42:36.677661 2017] [proxy_fcgi:error] [pid 60:tid 140423099528960] [client 197.245.88.228:21926] AH01071: Got error 'PHP message: PHP Warning:  require(/home/vcap/app/web/vendor/autoload.php): failed to open stream: No such file or directory in /home/vcap/app/web/webroot/index.php on line 27\nPHP message: PHP Fatal error:  require(): Failed opening required '/home/vcap/app/web/vendor/autoload.php' (include_path='../lib/php:/home/vcap/app/lib') in /home/vcap/app/web/webroot/index.php on line 27\n'
2017-02-21T18:42:36.70+0200 [APP/PROC/WEB/0]OUT 16:42:36 httpd   | 197.245.88.228 - - [21/Feb/2017:16:42:36 +0000] "GET / HTTP/1.1" 500 - vcap_request_id=0d1a4bd5-8b80-4d5a-6d1e-3f7eea6288d4 peer_addr=10.10.17.14
```

**Comment by dmikusa-pivotal** [comment] 2017-02-21 16:43
@lbayerl - your options.json is more similar to what we use in our unit tests.

```
{
    "COMPOSER_VENDOR_DIR": "vendor",
    "WEBDIR": "app/webroot",
    "LIBDIR": "library",
    "PHP_EXTENSIONS": ["pdo", "pdo_sqlite", "mcrypt"]
}
```

**Comment by jadekler** [comment] 2017-02-21 16:44
ps. When I `cf push` I am getting install notes:

```
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 16 installs, 0 updates, 0 removals
  - Installing cakephp/plugin-installer (0.0.15) Loading from cache
  - Installing aura/intl (3.0.0) Loading from cache
  - Installing cakephp/chronos (1.1.0) Loading from cache
  - Installing symfony/yaml (v3.2.4) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.4) Loading from cache
  - Installing symfony/console (v3.2.4) Loading from cache
  - Installing symfony/filesystem (v3.2.4) Loading from cache
  - Installing symfony/config (v3.2.4) Loading from cache
  - Installing robmorgan/phinx (v0.6.5) Loading from cache
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing zendframework/zend-diactoros (1.3.10) Loading from cache
  - Installing cakephp/cakephp (3.4.1) Loading from cache
  - Installing cakephp/migrations (1.6.7) Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.24) Loading from cache
Generating optimized autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
```

**Comment by dmikusa-pivotal** [comment] 2017-02-21 16:44
@jadekler - Need the staging logs.  Run `cf logs <app>` in one terminal then run `cf restage <app>` in the other.

**Comment by jadekler** [comment] 2017-02-21 16:44
Ah ok

**Comment by jadekler** [comment] 2017-02-21 16:44
```
jeandeklerk at Jeans-MacBook-Pro in /tmp/my_app_name
$ cf push
Using manifest file /tmp/my_app_name/manifest.yml

Updating app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK

Uploading my-cool-app...
Uploading app files from: /private/tmp/my_app_name
Uploading 150.3K, 138 files
Done uploading
OK

Stopping app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK

Starting app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
Downloading binary_buildpack...
Downloading nodejs_buildpack...
Downloading staticfile_buildpack...
Downloading java_buildpack...
Downloading ruby_buildpack...
Downloaded java_buildpack
Downloading php_buildpack...
Downloading go_buildpack...
Downloaded nodejs_buildpack
Downloaded ruby_buildpack
Downloading python_buildpack...
Downloading dotnet_core_buildpack...
Downloaded php_buildpack
Downloaded python_buildpack
Downloading dotnet_core_buildpack_beta...
Downloaded go_buildpack
Downloaded dotnet_core_buildpack
Downloaded dotnet_core_buildpack_beta
Downloaded binary_buildpack
Downloaded staticfile_buildpack
Creating container
Successfully created container
Downloading build artifacts cache...
Downloading app package...
Downloaded app package (317.1K)
Downloaded build artifacts cache (2M)
WARNING: buildpack version changed from 4.3.25 to 4.3.27
-------> Buildpack version 4.3.27
HTTPD 2.4.25
Installing HTTPD
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.25-linux-x64-bf8851c4.tgz] to [/tmp]
WARNING: The version defined in `composer.json` will be used.
Installing PHP
PHP 5.6.30
WARNING: A version of PHP has been specified in both `composer.json` and `./bp-config/options.json`.
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.30-linux-x64-c258884d.tgz] to [/tmp]
The extension 'intl' is not provided by this buildpack.
The extension 'pcre' is not provided by this buildpack.
The extension 'tokenizer' is not provided by this buildpack.
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.30-linux-x64-c258884d.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.3.2-9bd78ef1.phar] to [/tmp]
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 16 installs, 0 updates, 0 removals
  - Installing cakephp/plugin-installer (0.0.15) Loading from cache
  - Installing aura/intl (3.0.0) Loading from cache
  - Installing cakephp/chronos (1.1.0) Loading from cache
  - Installing symfony/yaml (v3.2.4) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.4) Loading from cache
  - Installing symfony/console (v3.2.4) Loading from cache
  - Installing symfony/filesystem (v3.2.4) Loading from cache
  - Installing symfony/config (v3.2.4) Loading from cache
  - Installing robmorgan/phinx (v0.6.5) Loading from cache
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing zendframework/zend-diactoros (1.3.10) Loading from cache
  - Installing cakephp/cakephp (3.4.1) Loading from cache
  - Installing cakephp/migrations (1.6.7) Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.24) Loading from cache
Generating optimized autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
Class App\Console\Installer is not autoloadable, can not call post-install-cmd script
Finished: [2017-02-21 16:40:59.289178]
Exit status 0
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (2M)
Uploaded droplet (56M)
Uploading complete
Destroying container
Successfully destroyed container

1 of 1 instances running

App started


OK

App my-cool-app was started using this command `$HOME/.bp/bin/start`

Showing health and status for app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: my-cool-app.cfapps.io
last uploaded: Tue Feb 21 16:40:35 UTC 2017
stack: cflinuxfs2
buildpack: php 4.3.27

     state     since                    cpu    memory        disk           details
#0   running   2017-02-21 06:41:29 PM   0.0%   1012K of 1G   110.4M of 1G
```

**Comment by jadekler** [comment] 2017-02-21 16:44
@dmikusa-pivotal

**Comment by lbayerl** [comment] 2017-02-21 16:45
Class App\Console\Installer is not autoloadable, can not call post-install-cmd script !!!

**Comment by jadekler** [comment] 2017-02-21 16:46
Ahhh. I'm a php noob, what's the deal with that? I note that my `composer.json` was autogenerated by `bake` with:

```
"post-install-cmd": "App\\Console\\Installer::postInstall",
```

**Comment by lbayerl** [comment] 2017-02-21 16:48
I suggest you give it a try, read what's going on here - and close this issue unless it's a real one with PHP buildpack. It's most probably not.

**Comment by jadekler** [comment] 2017-02-21 16:49
@lbayerl Give what a try, specifically?

**Comment by lbayerl** [comment] 2017-02-21 16:52
read why `bake` was autogenerating this line, what it is supposed to do, understand how this relates to the composer install process and cake's autoloading and finally (but at that point your issue is probably solved) how this fits in the composer install process of this buildpack.

**Comment by jadekler** [comment] 2017-02-21 17:00
So, that problem is avoided by simply removing the `scripts` section of my package.json. Separate problem opening in new thread..

**Comment by jadekler** [comment] 2017-02-21 17:15
Nevermind, this is still a problem. /shrug. Here is new staging logs with a simpler `options.json` @dmikusa-pivotal:

```
$ cf delete my-cool-app && cf push

Really delete the app my-cool-app?> yes
Deleting app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK
Using manifest file /tmp/my_app_name/manifest.yml

Creating app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK

Using route my-cool-app.cfapps.io
Binding my-cool-app.cfapps.io to my-cool-app...
OK

Uploading my-cool-app...
Uploading app files from: /private/tmp/my_app_name
Uploading 148.5K, 135 files
Done uploading
OK

Starting app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
Downloading binary_buildpack...
Downloading python_buildpack...
Downloading java_buildpack...
Downloading ruby_buildpack...
Downloading dotnet_core_buildpack...
Downloaded binary_buildpack
Downloading php_buildpack...
Downloaded ruby_buildpack
Downloading dotnet_core_buildpack_beta...
Downloaded java_buildpack
Downloading staticfile_buildpack...
Downloaded python_buildpack
Downloading nodejs_buildpack...
Downloaded dotnet_core_buildpack
Downloading go_buildpack...
Downloaded go_buildpack
Downloaded php_buildpack
Downloaded dotnet_core_buildpack_beta
Downloaded staticfile_buildpack
Downloaded nodejs_buildpack
Creating container
Downloading app package...
Successfully created container
Downloaded app package (307K)
-------> Buildpack version 4.3.27
Installing HTTPD
HTTPD 2.4.25
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.25-linux-x64-bf8851c4.tgz] to [/tmp]
Installing PHP
PHP 7.0.15
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php7_php7-7.0.15-linux-x64-446149ae.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php7_php7-7.0.15-linux-x64-446149ae.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/dcceb5748f8f40c08a6674e49d6222e2/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.3.2-9bd78ef1.phar] to [/tmp]
PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
Loading composer repositories with package information
Updating dependencies
Package operations: 16 installs, 0 updates, 0 removals
  - Installing cakephp/plugin-installer (0.0.15) Downloading

     application composer.json file to add the post-autoload-dump hook.
     See the changes in https://github.com/cakephp/app/pull/216 for more

     info.

  - Installing mobiledetect/mobiledetectlib (2.8.24) Downloading
  - Installing psr/http-message (1.0.1) Downloading
  - Installing symfony/yaml (v3.2.4) Downloading
  - Installing symfony/debug (v3.2.4) Downloading
  - Installing symfony/polyfill-mbstring (v1.3.0) Downloading
  - Installing symfony/console (v3.2.4) Downloading
  - Installing symfony/filesystem (v3.2.4) Downloading
  - Installing symfony/config (v3.2.4) Downloading
  - Installing robmorgan/phinx (v0.6.5) Downloading
  - Installing cakephp/migrations (1.6.7) Downloading
Writing lock file
Generating autoload files
Finished: [2017-02-21 17:14:11.671032]
     Action required!
     The CakePHP plugin installer has been changed, please update your
  - Installing aura/intl (3.0.0) Downloading
  - Installing zendframework/zend-diactoros (1.3.10) Downloading
  - Installing psr/log (1.0.2) Downloading
  - Installing cakephp/chronos (1.1.0) Downloading
  - Installing cakephp/cakephp (3.4.1) Downloading
Exit status 0
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (8.9M)
Uploaded droplet (64.2M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App my-cool-app was started using this command `$HOME/.bp/bin/start`

Showing health and status for app my-cool-app in org denver-labs / space development as jdeklerk@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: my-cool-app.cfapps.io
last uploaded: Tue Feb 21 17:13:11 UTC 2017
stack: cflinuxfs2
buildpack: php 4.3.27

     state     since                    cpu    memory        disk           details
#0   running   2017-02-21 07:14:42 PM   0.0%   15.2M of 1G   197.9M of 1G
```

**Comment by lbayerl** [comment] 2017-02-22 10:45
To avoid 'errors' by simply deleting stuff while not knowing what the deleted stuff was responsible for isn't - well - not ideal. Kindly follow my hint.

And just as an example: my git code which I provided you is nothing else then pushing the `Symfony Standard Example Application` to Cloud Foundry - as you can see, it's not only a simple `cf push` and crossing fingers.

**Comment by Sonik511** [comment] 2017-03-05 07:04
An easy way to solve this is to bypass composer. On cloudfoundry, it gets the composer.json and tries to download all dependencies and fails. So instead download all the dependencies on your local machine and then push that whole thing without composer. For this remove the composer.lock and composer.json files from your folder and then do a cf push.

Do the push using 
cf push -b https://github.com/cloudfoundry/php-buildpack.git

additionally you might have to add a  ".bp-config/option.json" file with various extensions that you need to enable for php. For example
{
"PHP_EXTENSIONS" : ["mbstring","intl","pdo","pgsql","pdo_pgsql"] 
}

**Comment by sclevine** [comment] 2017-06-23 02:28
Closing this due to inactivity.

**Closed by sclevine** 2017-06-23 02:28 UTC
Labels: unscheduled

**Comment by pburkholder** [comment] 2018-01-22 19:19
#243 might be related
