### ISSUE TITLE
Buildpack issues with Mediawiki

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry/php-buildpack#214] opened 2017-06-22 10:00 UTC
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
 
```
{
  "name": "",
  "build": "",
  "support": "https://support.run.pivotal.io",
  "version": 0,
  "description": "Cloud Foundry sponsored by Pivotal",
  "authorization_endpoint": "https://login.run.pivotal.io",
  "token_endpoint": "https://uaa.run.pivotal.io",
  "min_cli_version": "6.22.0",
  "min_recommended_cli_version": "latest",
  "api_version": "2.84.0",
  "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
  "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
  "app_ssh_oauth_client": "ssh-proxy",
  "routing_endpoint": "https://api.run.pivotal.io/routing",
  "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443"
}
```

`cf version 6.25.0+787326d95.2017-02-28`

**What version of the buildpack are you using?**

`php_buildpack-cached-v4.3.33.zip`

**If you were attempting to accomplish a task, what was it you were attempting to do?**

I tried to install Mediawiki 1.28.2, from a tarball, on PWS.

**What did you expect to happen?**

I expected the Mediawiki installer to work easily with the CF PHP buildpack.

**What was the actual behavior?**

Using the CF PHP buildpack, I can't get the Mediawiki installer past "Installing some external dependencies (e.g. via composer) is required."

Using the Heroku PHP buildpack, I got useful guidance, and I managed to get the installer working. When I attempted to stage:

1. it complained about a missing composer.lock. [I generated one.](https://github.com/pronoiac/mediawiki_on_pws/blob/master/composer.lock)

2. it warned about `/vendor` in the source tree, and that it could confuse composer. I ran `rm -rf vendor/`.

Then, it stages, and the installer works, but only with the Heroku buildpack.

I'm sure that Mediawiki is responsible for some of this, but I lack the context to untangle the various issues.

**Please confirm where necessary:**

* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment] 2017-06-23 16:00
Here's a guide for piwik: https://berndsgn.ch/run-piwik-on-cloud-foundry/
It's different, but maybe some of the concepts are similar?

Not sure when we'll have a chance to explore Mediawiki compatibility.

**Comment by dmikusa-pivotal** [comment] 2017-06-23 22:34
Here's what worked for me:

1.) Add `.cfignore`.  Insert one line `vendor` so that `cf push` does not upload the vendor directory.  This is optional but saves you upload bandwidth.

2.) Make `.bp-config/options.json`.  Insert the following:

```
{
    "COMPOSER_VENDOR_DIR": "{BUILD_DIR}/htdocs/vendor"
}
```

This tells the build pack to put composer installed dependencies into the `htdocs/vendor` directory which is where Mediawiki seems to expect them.

2.) Make `.bp-config/php/php.ini.d/wiki.ini`.  Insert the following:

```
extension=mysqli.so
extension=apcu.so
```

This will enable the mysqli and apcu extensions.  You may need to add additional other extensions, perhaps if you use a different database.

For what it's worth, the build pack detects and enables the following extensions automatically so you don't need to manually enable these.

```
extension=bz2.so
extension=zlib.so
extension=curl.so
extension=mcrypt.so
extension=openssl.so
extension=mbstring.so
```

3.) I created the following manifest.yml file.

```
---
applications:
- name: php-wiki
  memory: 128M
  instances: 1
  path: .
  buildpack: php_buildpack
  services:
  - p-mysql-ded
```

The main points here are to set the PHP build pack and to bind a MySQL service.

4.) `cf push` the app.

5.) Run through the installer & download the configuration file.

6.) Copy the downloaded `LocalSettings.php` to the root of your project.  Run `cf push` again.

You should now be able to access your Mediawiki install.  As a side note, do be careful with any files that you upload.  The won't persist across future `cf push`'s or even your app getting restarted since CF doesn't have a persistent file system.

Hope that helps!

**Comment by pronoiac** [comment] 2017-07-07 18:13
@dmikusa-pivotal: Have you posted these directions elsewhere? I've already written up [how to use the Heroku buildpack to get the Mediawiki installer going,](https://github.com/pronoiac/mediawiki_on_pws) and I could (with your permission) add your directions re: the CF buildpack.

**Comment by dmikusa-pivotal** [comment] 2017-07-07 18:19
@pronoiac - I have not.  Feel free to write them up and share.  Due to time constraints, it's probably not something I'd get to for a while, and I'd rather have them out there for people to use that waiting on me.  Thanks!

**Comment by pronoiac** [comment] 2017-07-07 23:24
@dmikusa-pivotal: Walking through your directions, I got a weirdly unstyled installer; the JS console warned `Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://[redacted]/index.php?css=1".` It looks like that url is serving up html. Does this sound familiar?

**Comment by dmikusa-pivotal** [comment] 2017-07-08 18:32
@pronoiac - I didn't see this last time, but I just retried my instructions and am seeing the same issue.  I thought it might be due to stuff in my DB from the previous install, but clearing that out didn't help.  I did the same with my cookies and browser side data.  Clearing that out didn't help.  

I don't know the software that well, but it seems like a problem with MediaWiki.  MediaWiki is complaining that there is no `LocalSettings.php` file, however, there shouldn't be one because we haven't done the install yet.  That file gets generated by the install and we upload it after the install runs.

Looking at what's different since the last time I ran, it does seem like there is a new PHP build pack out on PWS, so I tried with v4.3.35.  Low and behold the CSS is working again.  There's not much difference between the two build packs.  I'm using PHP 5.6.30 with both.  It's also the same version of Composer.  The only notable difference is HTTPD has been upgraded to 2.4.26.  I'm not sure off hand how that could cause this issue though.

For now, try v4.3.35 and it should work.

@sclevine - Seeing some weird differences with PHP build pack 4.3.36 using the instructions above.  Maybe something you want to look into more?

**Comment by dmikusa-pivotal** [comment] 2017-07-08 18:44
It also works fine with Nginx, so if you set `.bp-config/options.json` to this, it should work with the latest build pack.

```
{
    "COMPOSER_VENDOR_DIR": "{BUILD_DIR}/htdocs/vendor",
    "WEB_SERVER": "nginx"
}
```

@sclevine - Further evidence that something has changed with HTTPD 2.4.26 that might affect how applications deployed by the build pack run.

**Comment by sclevine** [comment] 2017-07-09 17:34
Thanks @dmikusa-pivotal, prioritizing this issue to investigate a possible regression.

**Comment by sclevine** [comment] 2017-07-12 14:38
Issue likely identified in #216.

**Comment by sclevine** [comment] 2017-07-14 13:37
Fixed in the latest release by bumping Apache.

**Closed by sclevine** 2017-07-14 13:37 UTC
Labels: enhancement, unscheduled

**Comment by ajknol** [comment] 2018-01-23 15:17
@dmikusa-pivotal: I have followed your instructions to install mediawiki on CF, but get the following error: 

Required components
You are missing a required extension to PHP that MediaWiki requires to run. Please install:
fileinfo (more information)

How do I install fileinfo?

**Comment by dmikusa-pivotal** [comment] 2018-01-24 04:49
Add `extension=fileinfo.so` to step #2 above.  It exists but just needs to be turned on in php.ini.

Dan

**Comment by ajknol** [comment] 2018-01-24 06:25
Hi Dan, thanks for your reply. Yesterday I tried to add the fileinfo.so to wiki.ini. The error remains, however. Do you have a suggestion what I can do to solve this?

**Comment by dmikusa-pivotal** [comment] 2018-01-25 17:00
I'm not sure.  Check `phpinfo();` and confirm if the extension is being loaded.  That should break things down and let us know if it's an issue loading the extension or if it's an issue with the app detecting the loaded extension.

I did a quick check with an app and I'm able to enable the fileinfo extension.

<img width="979" alt="screen shot 2018-01-25 at 12 00 25 pm" src="https://user-images.githubusercontent.com/4643262/35401395-5ecc9fa0-01c7-11e8-84b1-fdc02acbf237.png">

**Comment by ajknol** [comment] 2018-01-27 09:59
@dmikusa-pivotal: thanks, Fileinfo works now via an override of php.ini in the .bp-config/php/ dir.

Arjan

**Comment by dmikusa-pivotal** [comment] 2018-01-29 15:49
@ajknol - Be careful overriding the entire php.ini file.  This can have unintended side effects.  

It's much better to use the method [here](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#php-extensions).  This adds additional config instead of overriding everything.  This method should work with any recent version of the PHP buildpack.

If you absolutely have to override the whole file, which you shouldn't need to do just to enable extensions, then start with the [php.ini file default use by the buildpack](https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/php). This has placeholders in it, which are required for the buildpack to properly configured PHP.  It should help to reduce side effects and problems.

Hope that helps!

**Comment by bbodenmiller** [comment] 2018-11-10 03:12
> You should now be able to access your Mediawiki install. As a side note, do be careful with any files that you upload. The won't persist across future cf push's or even your app getting restarted since CF doesn't have a persistent file system (by default).

What kind of solutions have folks put in place with PCF to handle file uploads from MediaWiki?

**Comment by ajknol** [comment] 2018-11-12 07:31
> > You should now be able to access your Mediawiki install. As a side note, do be careful with any files that you upload. The won't persist across future cf push's or even your app getting restarted since CF doesn't have a persistent file system (by default).
> 
> What kind of solutions have folks put in place with PCF to handle file uploads from MediaWiki?

I have mounted an external fileshare to which uploaded files are saved. https://docs.cloudfoundry.org/devguide/services/using-vol-services.html.
