### ISSUE TITLE
Request for php extension: sodium

### ISSUE THREAD

**Issue by noo-zh** [cloudfoundry/php-buildpack#236] opened 2017-12-20 23:53 UTC
Hi,

since the [sodium](http://php.net/manual/en/book.sodium.php) extension is included as a core extension in PHP 7.2, it would be great to have an option to use it. It's weird because normally it works automatically - no instalation is needed - but not with latest buildpack.

Thanks for checking that.

**Comment by sclevine** [comment] 2018-02-22 02:29
@dgodd

**Comment by dgodd** [comment] 2018-02-22 13:17
Duplicate of https://github.com/cloudfoundry/php-buildpack/issues/237

**Closed by dgodd** 2018-02-22 13:17 UTC
Labels: unscheduled

**Comment by dmikusa-pivotal** [comment] 2018-08-28 13:18
This isn't a duplicate as far as I can tell. This is asking for the sodium extension, while #237 is asking for Argon2 support in PHP's password hashing library. I have a PR for binary-builder which should take care of both this and #237.

**Comment by dmikusa-pivotal** [comment] 2018-08-28 13:54
@noo-zh - I have submitted a PR for this as well. If you want to test, you can use this buildpack which will be available until the PR is merged.

https://github.com/dmikusa-pivotal/php-buildpack.git#argon2-enabled

It only packages PHP 7.2.9, so you need to specifically request that version.

Ex:

```
$ cat .bp-config/options.json
{
    "PHP_VERSION": "7.2.9"
}
```

You also need to enable the extension:

```
$ cat .bp-config/php/php.ini.d/extensions.ini
extension=sodium.so
```

`phpinfo()` should then report the extension as available.

![screen shot 2018-08-28 at 9 54 14 am](https://user-images.githubusercontent.com/4643262/44727594-632e3380-aaa8-11e8-8590-795ebcb841a4.png)

**Comment by noo-zh** [comment] 2018-09-01 12:28
@dmikusa-pivotal Many thanks! :+1: Unfortunately I'm unable to deploy this buildpack on IBM Cloud. I'm not sure why :disappointed:... Will try again later - maybe some network issues. Before my try, I also switched buildpack from #v4.3.57 to #v4.3.60 and it worked... but not #argon2-enabled. Do you maybe have any ideas? 

```
zdenek@acer:~/Git/cf-test$ ibmcloud cf push -b https://github.com/cloudfoundry/php-buildpack.git#argon2-enabled
Invoking 'cf push -b https://github.com/cloudfoundry/php-buildpack.git#argon2-enabled'...


Pushing from manifest to org ***** / space test as zde*****@*****.com...
Using manifest file /home/zdenek/Git/cf-test/manifest.yml
Getting app info...
Updating app with these attributes...
  name:                cf-test
  path:                /home/zdenek/Git/cf-test
- buildpack:           https://github.com/cloudfoundry/php-buildpack.git#v4.3.60
+ buildpack:           https://github.com/cloudfoundry/php-buildpack.git#argon2-enabled
  command:             $HOME/.bp/bin/start
  disk quota:          512M
  health check type:   port
  instances:           1
  memory:              64M
  stack:               cflinuxfs2
  routes:
    cf-test-1.eu-gb.mybluemix.net

Updating app cf-test...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 21.03 KiB / 21.03 KiB [=========================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Stopping app...

Staging app and tracing logs...
   Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 creating container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 successfully created container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   Downloading build artifacts cache...
   Downloading app package...
   Downloaded build artifacts cache (1.1K)
   Downloaded app package (42K)
   Failed to clone git repository at https://github.com/cloudfoundry/php-buildpack.git
   Exit status 1
   Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 stopping instance a2213d03-6a5a-4903-a32e-34fff892335f
   Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 destroying container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 successfully destroyed container for instance a2213d03-6a5a-4903-a32e-34fff892335f
Error staging application: Staging error: staging failed
FAILED
```

Log:
```
2018-09-01T14:11:06.12+0200 [STG/0] OUT Uploading droplet, build artifacts cache...
   2018-09-01T14:11:06.12+0200 [STG/0] OUT Uploading droplet...
   2018-09-01T14:11:06.12+0200 [STG/0] OUT Uploading build artifacts cache...
   2018-09-01T14:11:06.18+0200 [STG/0] OUT Uploaded build artifacts cache (1.1K)
   2018-09-01T14:11:08.08+0200 [API/4] OUT Creating droplet for app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a
   2018-09-01T14:11:20.68+0200 [STG/0] OUT Uploaded droplet (96.9M)
   2018-09-01T14:11:20.70+0200 [STG/0] OUT Uploading complete
   2018-09-01T14:11:20.74+0200 [STG/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b stopping instance 03a3df2c-6a2f-4e39-8e78-b45dbcd041f5
   2018-09-01T14:11:20.74+0200 [STG/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b destroying container for instance 03a3df2c-6a2f-4e39-8e78-b45dbcd041f5
   2018-09-01T14:11:22.02+0200 [CELL/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b creating container for instance e5e54394-8ffa-4c3f-63f0-98c8
   2018-09-01T14:11:22.54+0200 [CELL/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b successfully created container for instance e5e54394-8ffa-4c3f-63f0-98c8
   2018-09-01T14:11:22.61+0200 [STG/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b successfully destroyed container for instance 03a3df2c-6a2f-4e39-8e78-b45dbcd041f5
   2018-09-01T14:11:30.67+0200 [CELL/0] OUT Starting health monitoring of container
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: using the "epoll" event method
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: nginx/1.14.0
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) 
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: OS: Linux 4.4.0-109-generic
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: getrlimit(RLIMIT_NOFILE): 16384:16384
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: start worker processes
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: start worker process 68
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: start worker process 69
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: start worker process 70
   2018-09-01T14:11:31.08+0200 [APP/PROC/WEB/0] OUT 12:11:31 nginx   | 2018/09/01 12:11:31 [notice] 67#0: start worker process 71
   2018-09-01T14:11:31.09+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | Cannot load Zend OPcache - it was already loaded
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'bz2' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'zlib' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'curl' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'exif' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'pgsql' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'geoip' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'rdkafka' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'redis' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'phpiredis' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'gnupg' already loaded in Unknown on line 0
   2018-09-01T14:11:31.10+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: PHP message: PHP Warning:  Module 'soap' already loaded in Unknown on line 0
   2018-09-01T14:11:31.16+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: fpm is running, pid 74
   2018-09-01T14:11:31.16+0200 [APP/PROC/WEB/0] OUT 12:11:31 php-fpm | [01-Sep-2018 12:11:31] NOTICE: ready to handle connections
   2018-09-01T14:11:32.77+0200 [CELL/0] OUT Container became healthy
   2018-09-01T14:11:43.57+0200 [API/1] OUT Updated app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a ({"buildpack"=>"https://github.com/cloudfoundry/php-buildpack.git#argon2-enabled", "disk_quota"=>512, "health_check_http_endpoint"=>"", "health_check_type"=>"port", "instances"=>1, "memory"=>64, "name"=>"cf-test", "state"=>"STARTED"})
   2018-09-01T14:11:44.27+0200 [API/8] OUT Uploading bits for app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a
   2018-09-01T14:11:47.90+0200 [CELL/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b stopping instance e5e54394-8ffa-4c3f-63f0-98c8
   2018-09-01T14:11:47.90+0200 [API/3] OUT Updated app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a ({"state"=>"STOPPED"})
   2018-09-01T14:11:47.90+0200 [CELL/SSHD/0] OUT Exit status 0
   2018-09-01T14:11:47.92+0200 [APP/PROC/WEB/0] OUT Exit status 143
   2018-09-01T14:11:47.95+0200 [CELL/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b destroying container for instance e5e54394-8ffa-4c3f-63f0-98c8
   2018-09-01T14:11:48.12+0200 [PROXY/0] OUT Exit status 137
   2018-09-01T14:11:48.51+0200 [CELL/0] OUT Cell cb012785-8bc0-4c56-aac6-8757483c9c5b successfully destroyed container for instance e5e54394-8ffa-4c3f-63f0-98c8
   2018-09-01T14:11:48.64+0200 [API/5] OUT Creating build for app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a
   2018-09-01T14:11:49.15+0200 [API/5] OUT Updated app with guid 5f73dd7d-ca31-4f83-a934-69ce98750f0a ({"state"=>"STARTED"})
   2018-09-01T14:11:49.62+0200 [STG/0] OUT Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 creating container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   2018-09-01T14:11:50.30+0200 [STG/0] OUT Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 successfully created container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   2018-09-01T14:11:51.61+0200 [STG/0] OUT Downloading build artifacts cache...
   2018-09-01T14:11:51.61+0200 [STG/0] OUT Downloading app package...
   2018-09-01T14:11:51.70+0200 [STG/0] OUT Downloaded build artifacts cache (1.1K)
   2018-09-01T14:11:51.70+0200 [STG/0] OUT Downloaded app package (42K)
   2018-09-01T14:11:53.30+0200 [STG/0] ERR Failed to clone git repository at https://github.com/cloudfoundry/php-buildpack.git
   2018-09-01T14:11:53.32+0200 [STG/0] OUT Exit status 1
   2018-09-01T14:11:53.35+0200 [STG/0] OUT Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 stopping instance a2213d03-6a5a-4903-a32e-34fff892335f
   2018-09-01T14:11:53.35+0200 [STG/0] OUT Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 destroying container for instance a2213d03-6a5a-4903-a32e-34fff892335f
   2018-09-01T14:11:53.87+0200 [STG/0] OUT Cell 7bded498-2119-4131-9b15-c2ed4faa6f00 successfully destroyed container for instance a2213d03-6a5a-4903-a32e-34fff892335f

```

**Comment by noo-zh** [comment] 2018-09-15 09:04
> @dmikusa-pivotal Many thanks! +1 Unfortunately I'm unable to deploy this buildpack on IBM Cloud. I'm not sure why disappointed... Will try again later - maybe some network issues. Before my try, I also switched buildpack from #v4.3.57 to #v4.3.60 and it worked... but not #argon2-enabled. Do you maybe have any ideas?

Well, that was my fault. I actually used another repository :smiley: 

Anyway, like Argon2, Sodium works perfectly. Great work and looking forward PR to be merged.
