### ISSUE TITLE
Installing buildpack on Vagrant machine for local testing

### ISSUE THREAD

**Issue by wesrice** [cloudfoundry/php-buildpack#133] opened 2016-02-19 16:13 UTC
Forgive me for this not really an issue, but more of a question. 

I develop locally with a Vagrant machine and push to my Cloud Foundry provider. I've been mimicking my buildpack config in my Vagrant config. Ideally, I'd like to actually install my buildpack on my vm and actually use my buildpack config instead of mimicking it.

I would imagine that this would involve pulling this repo in the provisioning process, installing buildpack dependencies, and then targeting a script (or few) within the buildpack to run the build. However, I'm not quite sure what this entails.

Am I better off just using my current mimicked setup and maintaining multiple config files or is there a better way to do this?

**Comment by dmikusa-pivotal** [comment] 2016-02-19 16:32
You might try https://github.com/pivotal-cf/micropcf

It's still pretty early day's, but the plan is for this to make a super easy way for you to do local dev.

**Comment by wesrice** [comment] 2016-02-19 17:23
@dmikusa-pivotal That looks promising, but wouldn't that still require you to `cf push` your app to your vm?

I guess I was thinking something more along the lines of Vagrant syncing the working directory with the vm's `/home/vcap/app`, so that any file changes in the local directory are immediately synced.

**Comment by flavorjones** [comment] 2016-02-19 17:33
ping to @dwadden and @sclevine on the microPCF team

**Comment by dmikusa-pivotal** [comment] 2016-02-19 17:41
@wesrice - you're right, it would still have the same workflow.  Short of doing a `cf push` and letting the platform stage for you, you're going to need to manually stage the app.  By that, I mean either manually run the build pack scripts or manually perform a similar set of steps.

One option I haven't tried would be to stage your app to CF, download the droplet and extract that to a local VM.  The droplet contains everything needed to run your app.  If you extract it to `/home/vcap` in a VM, it might give you what you need to run a local env.  Getting your hands on a droplet is easier said than done at the moment.  You might be able to use the [CF API](http://apidocs.cloudfoundry.org/230/droplets_(experimental)/get_a_droplet.html) but more likely, you'd need to push to something like microcf, ssh in and copy out the droplet that's produced.  Anyway, just brainstorming here.  Not saying this is necessarily a good idea.

Dan

**Comment by wesrice** [comment] 2016-02-19 19:16
@dmikusa-pivotal I'm just brainstorming too, but in theory I could:

1. `vagrant up` to provision micropcf
2. `cf push` my app micropcf
3. Add the following to the vagrant file

        config.vm.synced_folder "./path/to/my/working/directory", "/home/vcap/app", owner: "vcap", group: "vcap"

4. `vagrant reload` micropcf

Does this seem plausible? I'll play around with this some.

**Comment by sclevine** [comment] 2016-02-19 19:42
@wesrice This will not work. `config.vm.synced_folder` will not automatically sync your app into `/home/vcap/app` of your intended app container. Unless you manually configure rsync/scp to sync your files with a specific app container (see [here](https://github.com/cloudfoundry-incubator/diego-ssh#cloud-foundry-via-cloud-controller-and-uaa)), you'll need to push your app every time you want to update it.

Our team has done some work on a tool to continuously sync an application with a running CF cluster, but finishing this tool is not a current priority.

If you'd like to use MicroPCF to test custom buildpacks, you can use the `cf create-buildpack` command with your custom buildpack against a MicroPCF VM.

**Comment by jtarchie** [comment] 2016-02-22 14:01
@wesrice, what workflow are you solving by working on a vagrant machine and then `cf push`ing?

Trying to reproduce buildpacks locally is actually harder than thought. I'd recommend highly using a microPCF and just `cf push`.

**Comment by wesrice** [comment] 2016-02-22 16:48
@jtarchie, 

My goal is to have 100% parity between my Pivotal Web Services cloud foundry instances and my local vm. I want to use a local vm with synced folders for development so I can instantly see my changes after saving a file, without having to  `cf push` to microPCF. Having to run a command after every file change seems possible (http://stackoverflow.com/questions/20802285/run-shell-script-when-saving-a-file-in-sublime-text-3), but it seems a bit overkill. I'm also afraid the post-save shell script automation wouldn't scale well as applications are distributed to additional developers.

I could have Vagrant provision my vm utilizing my custom config files in .bg-config, but these files do not represent the full configuration of services, as they are merged with the default files of this buildpack. 

So, for now, I am maintaining two separate configs: one for this buildpack and one for my local vm. I was thinking this could be mitigated by actually using the buildpack to configure my vm, but that seems out of reach at the moment.

Perhaps my expectations are wrong and I should be trying to implement a different workflow? I'm open to suggestions.

**Comment by jtarchie** [comment] 2016-02-22 16:58
Ideally, you'd be able to work on your app in your normal development environment (vagrant free) and be able to `cf push` with minimal configuration changes. Were you experiencing a problem when trying to develop this way?

**Comment by flavorjones** [comment] 2016-02-22 18:27
> My goal is to have 100% parity between my Pivotal Web Services cloud foundry instances and my local vm

This sounds exactly like what microPCF is intended to provide, in one way or another. @sclevine or @dwadden, are you interested in better understanding @wesrice's workflow needs?

**Comment by RochesterinNYC** [comment] 2016-04-04 16:36
@wesrice microPCF is now [PCFDev](https://github.com/pivotal-cf/pcfdev) and there is a public download available at https://network.pivotal.io/products/pcfdev

**Comment by RochesterinNYC** [comment] 2016-04-11 19:36
Closing this issue as it seems to be resolved. Please let us know if you require further assistance.

**Closed by RochesterinNYC** 2016-04-11 19:36 UTC
